#!/bin/bash

#  Copyright 2023 endro mei asmoro <emasmoro@gmail.com>
# 
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#27.09.2023
#hitung kebutuhan pasir semen batu
#https://berita.99.co/cara-menghitung-kebutuhan-semen-dan-pasir/

file_konfigurasi=$(echo $HOME)/Music/bangunan/configuration

buat_bariskosong() {
	echo ""
}

buat_masukanpanjangdanlebardinding() {
	buat_bariskosong
	#read -p "Masukkan panjang dinding (meter) : " panjang 
	#ead -p "Masukkan lebar dinding (meter) : " lebar 
		panjang=11
		lebar=4
}

buat_hilangkantitik() {
	yangdihitung=$1
	angkadilbelakangkoma=$(echo $yangdihitung | sed 's/[.]/  /g' | awk '{print $2}')
	if [[ $angkadilbelakangkoma -ge 30 ]]; then
		tambahan=1
		else
		tambahan=0
	fi
}

buat_pembulatansetengah() {
	yangdihitung=$1
	angkadilbelakangkoma=$(echo $yangdihitung | sed 's/[.]/  /g' | awk '{print $2}')
	angkadilbelakangkomasementara=$(echo $angkadilbelakangkoma | cut -b 1-2)
	cekadanol=$(echo $angkadilbelakangkomasementara | cut -b 1)
	nilainya=$(echo $angkadilbelakangkomasementara | cut -b 2)
	if [[ $cekadanol -eq 0 ]]; then
		angkadilbelakangkomasementara= $nilainya
	fi
	angkadilbelakangkoma=$angkadilbelakangkomasementara
	if [[ $angkadilbelakangkoma -ge 30 ]]; then
		tambahansetengah=1
		else
		tambahansetengah=0
	fi
}

buat_angkadidepan() {
	yangdihitung=$1
	angkadildepankoma=$(echo $yangdihitung | sed 's/[.]/  /g' | awk '{print $1}')
}

buat_hitungluas() {
		panjang=$1
		lebar=$2
		luas=$(echo "$panjang * $lebar" | bc -l)
}

buat_rumushitungsemen()  {
	jumlah_kebutuhansemen=$1
	jumlah_satusaksemen=$2

	hitung_luasdinding=$(echo  "$panjang * $lebar" | bc -l )
	hitung_volumesemen=$( echo "$hitung_luasdinding * $jumlah_kebutuhansemen")
	hitung_jumlahsemen=$(echo "scale=2;$hitung_volumesemen / $jumlah_satusaksemen " | bc -l)
	buat_hilangkantitik $hitung_jumlahsemen
	buat_angkadidepan $hitung_jumlahsemen
	hitung_jumlahsemensementara=$(echo " $angkadildepankoma + $tambahan" | bc -l)
	
}

buat_rumushitungpasir() {
	jumlahpasir=$1
	totalpasir=$(echo "$jumlahpasir * $hitung_luasdinding" | bc -l)
}

buat_pasanganbatadancampuran() {
x1="Pasangan ½ Bata dengan Campuran"
x3="1 PC : 3 PP"
x4="1 PC : 4 PP"
x5="1 PC : 5 PP"
x6="1 PC : 6 PP"
x8="1 PC : 8 PP"
}

buat_hitungbiayamaterial() {
	echo "Perhitungan biaya Bahan bangunan"
	buat_rumushitungsemen $jumlahsemen 40
	echo "Kebutuhan total "
	echo "semen 40kg	:	$hitung_jumlahsemensementara sak"
	buat_rumushitungsemen $jumlahsemen 50
	echo "semen 50kg	:	$hitung_jumlahsemensementara sak"
	buat_rumushitungpasir $jumlahpasir
	buat_pembulatansetengah $totalpasir
	buat_angkadidepan $totalpasir
	echo "pasir		:	$(echo "$angkadildepankoma + $tambahansetengah" | bc -l) meter kubik"
}

buat_hitungsemendanpasir() {
	jumlahsemen=$1
	perbandingansemendanpasir=$2
	jumlahpasir=$3
	buat_bariskosong
	echo "Hasil perhitungan  dam kebutuhan semen dan pasir untuk "
	echo "$x1 $perbandingansemendanpasir"
	echo "================================="
	buat_rumushitungsemen $jumlahsemen 40
	echo "Panjangnya $panjang m Lebarnya $lebar m"
	buat_bariskosong
	echo "Luas dindingnya adalah	$hitung_luasdinding meter²"
	echo "Perhitungan total  "
	echo "semen 40kg	:	$hitung_jumlahsemen sak"
	buat_rumushitungsemen $jumlahsemen 50
	echo "semen 50kg	:	$hitung_jumlahsemen sak"
	buat_rumushitungpasir $jumlahpasir
	buat_pembulatansetengah $totalpasir
	buat_angkadidepan $totalpasir
	echo "pasir		:	$(echo "$totalpasir" ) meter kubik"
	#echo "Kebutuhan total pasir adalah	:	$(echo "$angkadildepankoma + $tambahansetengah" | bc -l) meter kubik"

	buat_bariskosong
	echo "$x1 $perbandingansemendanpasir"
	sleep 2
}

buat_menu() {
buat_pasanganbatadancampuran
buat_bariskosong
echo -n "Pilih salah Satu di Bawah ini 
perhitungan Dan kebutuhan Pasir dan Semen untuk Pasangan batubata
3] $x1 $x3
4] $x1 $x4
5] $x1 $x5
6] $x1 $x6
8] $x1 $x8
9] Keluar

keterangan : batu Bata ukuran 5 x 11 x 22 cm3
sesuai Dengan peraturan SNI 2008 -> "
read pilih
case $pilih in
3) buat_masukanpanjangdanlebardinding;buat_hitungsemendanpasir 14.37 "$x3" 0.04;buat_menu ;;
4) buat_masukanpanjangdanlebardinding;buat_hitungsemendanpasir 11.5  "$x4" 0.043;buat_menu ;;
5) buat_masukanpanjangdanlebardinding;buat_hitungsemendanpasir 9.68 "$x5" 0.045;buat_menu ;;
6) buat_masukanpanjangdanlebardinding;buat_hitungsemendanpasir 8.32 "$x6" 0.049;buat_menu ;;
8) buat_masukanpanjangdanlebardinding;buat_hitungsemendanpasir 6.5 "$x8" 0.05;buat_menu ;;
9) exit 0;;
*) echo $(clear);buat_menu;;
esac
}
buat_menu
